pub const TERMINATOR: char = '\0';
pub const NEWLINE: char = '\n';
pub const DOUBLE_QUOTE: char = '"';
pub const OPEN_PARENTHESIS: char = '(';
pub const CLOSE_PARENTHESIS: char = ')';
pub const UNDERSCORE: char = '_';
pub const GT: char = '>';
pub const EQUALS: char = '=';
pub const COLON: char = ':';
